### ISSUE TITLE
intro video

### ISSUE THREAD

**Issue by algazarra** [andrefbsantos/boilr-site#12]
@dllud what text should be in a fixed position of the video? I'm not so sure about what we have on the site's title...

**Comment by dllud** [comment]
Use the site's title, it's the most concise and clear description we have.

**Comment by cicardia** [comment]
<title>Boilr - Price alarms for Bitcoin, cryptocurrencies and bullion</title> sounds a bit flat... specially considering it will be in a fixed position the whole time.
or maybe, instead of just having that in a fixed position, we could use the video to slideshow some more text. Feedback, ideas and suggestions are more than welcome @andrefbsantos

**Comment by dllud** [comment]
Opted to avoid text in the video.
